# Travis-CI.org build script

arch: amd64          # optional, this is default, routes to a full VM
os: linux            # optional, this is default
dist: bionic         # Ubuntu 18.04 LTS

# python versions to test against...
language: python
python:
  - "3.8"
# scipy doesn't build
#  - "3.9-dev"
#  - "nightly"

install:
    - python --version
    # ubuntu's source extractor package renames the executable.
    - ln -s /usr/bin/sextractor ~/bin/sex
    - export PATH=${PATH}:~/bin
    - pip install sphinx
    - pip install numpy
    - pip install scipy
    # matplotlib problem saving jpg (in python3.5 only):
    # https://github.com/ipython/ipython/issues/8052
    - pip install "pillow<7"
    - pip install matplotlib
    - pip install astropy
    - pip install photutils
    - pip install coveralls
    - pip install fitsio==1.1.2
    - pip install cython
    - (cd $HOME && wget -nv http://www.fftw.org/fftw-3.3.8.tar.gz && tar xvzf fftw-3.3.8.tar.gz && cd fftw-3.3.8 && ./configure --enable-shared && make -j4 && sudo make install)
    - pip install galsim
    - (cd $HOME && git clone https://github.com/dstndstn/tractor.git && cd tractor && python setup-cython.py install --with-ceres)
    - if [ ! -d "$HOME/astrometry.net" ]; then (cd $HOME; git clone https://github.com/dstndstn/astrometry.net.git); fi
    - (cd $HOME/astrometry.net && git pull) || (rm -Rf $HOME/astrometry.net && cd $HOME && git clone https://github.com/dstndstn/astrometry.net.git);
    - (cd $HOME/astrometry.net && make && make py)
    - (cd $HOME && git clone https://github.com/legacysurvey/unwise_psf.git && cd unwise_psf && git checkout dr9.3)
    - (cd $HOME && git clone https://github.com/legacysurvey/legacypipe.git legacypipe && cd legacypipe && git checkout tags/DR9.6.7)
    - (cd $HOME && git clone https://github.com/desihub/desiutil.git desiutil && cd desiutil && python setup.py install)
    - export PYTHONPATH=$(pwd)/py:$HOME/legacypipe/py:$HOME/astrometry.net:$HOME/unwise_psf/py:${PYTHONPATH}
    - export PATH=$HOME/astrometry.net/solver:$HOME/astrometry.net/util:${PATH}

before_script:
    - mkdir -p $HOME/dust/maps
    - (cd $HOME/dust/maps && wget -c https://portal.nersc.gov/project/cosmo/temp/dstn/travis-ci/maps/SFD_dust_4096_ngp.fits)
    - (cd $HOME/dust/maps && wget -c https://portal.nersc.gov/project/cosmo/temp/dstn/travis-ci/maps/SFD_dust_4096_sgp.fits)
    - export DUST_DIR=$HOME/dust

script:
    - (cd py && coverage run tests/test_runbrick_legacypipe.py > log.out && coverage run -m pytest tests/ && coverage combine)

after_success:
    - (cd py && coveralls)
    - (cd py && ./codecov-upload.sh)

addons:
  apt:
    packages:
    - libnetpbm10
    - libnetpbm10-dev
    - netpbm
    - wcslib-dev
    - libcfitsio-dev
    - swig
    - gsl-bin
    - libgsl0-dev
    - libceres-dev
    - libcfitsio-bin # fpack
    - sextractor # for calibs
    - psfex # for calibs

cache:
  directories:
  - $HOME/astrometry.net
  - $HOME/dust
