version: 2.1
jobs:
  build-from-docker:
    docker:
      - image: adematti/obiwan:dr9.3
    steps:
      - run:
          name: CPU info
          command: cat /proc/cpuinfo
      - checkout
      - run:
          name: Tests
          command: |
              cd py
              export PYTHONPATH=${PYTHONPATH}:$(pwd)
              coverage run tests/test_runbrick.py
              coverage run -a -m pytest tests/

workflows:
  main:
    jobs:
      - build-from-docker
